sudo: false
language: node_js

node_js:
    - "6.1.0"
env:
    - CXX=g++-4.8

install:
    - rm -rf node_modules
    - yarn install

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
