jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '12.x'

      - script: |
          npm i -g yarn
          yarn install
          yarn build
        displayName: 'Building'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: ./release/
          artifactName: MyBuildOutputs

  - job: Windows
    pool:
      vmImage: 'windows-2019'

    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '12.x'

      - pwsh: |
          npm i -g yarn
          yarn install
          node --max-old-space-size=4096 ./node_modules/.bin/cross-env.cmd NODE_ENV=production ./node_modules/.bin/gulp publish
        displayName: 'Building'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: ./release/
          artifactName: MyBuildOutputs
