jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '11.x'

  - script: |
      npm i -g yarn
      yarn install
      yarn build
    displayName: 'Building'

- job: Windows
  pool:
    vmImage: 'windows-2019'
   
  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '11.x'
  
  - pwsh: |
      npm i -g yarn
      yarn install
      yarn build
    displayName: 'Building'
