jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm i -g yarn
      yarn install
      yarn build
    displayName: 'Building'

- job: Windows
  pool:
    vmImage: 'windows-2019'
    
  strategy:
    node_12:
      node_version: 12.x
   
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
  
  - script: |
      npm i -g yarn
      yarn install
      yarn build
    displayName: 'Building'
