name: CI

on: [push]

jobs: 
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '11.x'
    - name: Cache
      uses: actions/cache@v1.0.0
      with:
        path: node_modules
        key: ${{ matrix.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ matrix.os }}-${{ hashFiles('yarn.lock') }}
    - name: Install deps
      run: |
        npm i -g yarn
        yarn install
    - name: Build on UNIX
      if: startsWith(matrix.os, 'windows') == false
      run: yarn build
    - name: Build on Windows
      if: startsWith(matrix.os, 'windows')
      run: yarn build:windows
    - uses: actions/upload-artifact@master
      with:
        name: build-${{ matrix.os }}
        path: release
