name: CI

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '11.x'
    - name: Building
      run: |
        npm i -g yarn
        yarn install
        yarn build

  windows-build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '11.x'
    - name: Building
      run: |
        npm i -g yarn
        yarn install
        yarn build
  
